Searchable input
TurkNet/design-system pull request #103
Opened 2021-09-08 11:46 UTC by hidayatarg

2021-09-08 12:22 UTC, talatatac commented on src/components/SearchableInput/index.tsx
> +      <SearchableInputStyled
Bunun yerine input component'ini kullanmak daha iyi olurdu.

2021-09-08 12:24 UTC, talatatac commented on src/components/SearchableInput/index.tsx
> +    console.log('gelen value: ', value)
console.log silinebilir. Bu searchableinput'ta input'a focus olduğunda liste gelmesi gerekiyor sanırım. Value yazınca değildi.

2021-09-08 12:26 UTC, talatatac commented on src/components/SearchableInput/index.tsx
> +    opt => opt.value.toLowerCase().indexOf(search.toLowerCase()) !== -1
toLowerCase methodu yüzünden ingilizce türkçe karakter sorunu yaşar mıyız? Emin olamadım.

2021-09-08 12:34 UTC, talatatac commented on src/stories/SearchableInput.stories.tsx
> +
Birde buraya state ekleyebilir misin? Select value için

2021-09-09 07:21 UTC, recepkoseoglu requested changes

2021-09-09 07:21 UTC, recepkoseoglu commented on src/components/SearchableInput/index.tsx
> +  HTMLInputElement,
bunu vermene gerek yok

2021-09-09 07:21 UTC, recepkoseoglu commented on src/components/SearchableInput/styled.ts
> +  width: 100%;
bunun için styled oluşturmaya gerekk yoktu div ya da box kullanılabilir

2021-09-09 07:21 UTC, recepkoseoglu commented on src/components/SearchableInput/styled.ts
> +  background: #ffffff;
theme'deki renkleri kullanıyoruz

2021-09-09 07:21 UTC, recepkoseoglu commented on src/components/SearchableInput/styled.ts
> +  font-size: 1.3rem;
öçlüleri rem ya da em değil px kullanıyoruz

2021-09-09 07:21 UTC, recepkoseoglu commented on src/components/SearchableInput/styled.ts
> +  margin-left: -20px;
margin değerleri (-) vermiyoruz buna başka çözüm bulunmalı

2021-09-17 00:08 UTC, hidayatarg commented on src/components/SearchableInput/index.tsx
> +  HTMLInputElement,
@recepkoseoglu bunun yerinde 

```
export const SearchableInput: FC<SearchableInputProps> = ({
  ...props
}) => {
  return ( ) 

```
Seklinde mu olmasi gerekiyor

2021-09-27 12:18 UTC, ermanzohre requested changes

2021-09-27 12:18 UTC, ermanzohre commented on src/components/SearchableInput/styled.ts
> +  box-shadow: 5px 5px 5px rgba(0, 0, 0, 0.03), -5px 5px 5px rgba(0, 0, 0, 0.03);
tasarımda selectte box-shadow yok, buradan da kaldırabilirsin bence

2021-09-27 19:21 UTC, cuneytaskin approved these changes

2021-09-28 09:39 UTC, recepkoseoglu approved these changes

2021-09-28 09:39 UTC, recepkoseoglu commented on src/components/SearchableInput/styled.ts
> +  box-shadow: 5px 5px 5px rgba(0, 0, 0, 0.03), -5px 5px 5px rgba(0, 0, 0, 0.03);
tasarımda yok ama olması lazım

2021-09-28 09:42 UTC, ermanzohre approved these changes

2021-09-28 09:45 UTC, merged