add overflow menu component
TurkNet/design-system pull request #104
Opened 2021-09-09 14:49 UTC by talatatac

2021-09-10 10:11 UTC, ermanzohre approved these changes

2021-09-13 13:05 UTC, recepkoseoglu requested changes

2021-09-13 13:05 UTC, recepkoseoglu commented on src/components/OverflowMenu/styled.ts
> +    'active',
hover'da olması lazım

2021-09-16 07:55 UTC, recepkoseoglu requested changes

2021-09-16 07:55 UTC, recepkoseoglu commented on src/components/OverflowMenu/styled.ts
> +export interface OverflowMenuItemStyledProps {
@talatatac buna bakabilir misin düzeltirsen merge edebiliriz

2021-09-16 10:46 UTC, recepkoseoglu requested changes

2021-09-16 10:46 UTC, recepkoseoglu commented on src/components/OverflowMenu/OverflowMenuItem.tsx
> +export interface OverflowMenuItemProp {
OverflowMenuItemProps olucak

2021-09-16 11:09 UTC, recepkoseoglu approved these changes

2021-09-16 11:10 UTC, merged