71 table
TurkNet/design-system pull request #117
Opened 2021-09-24 11:51 UTC by ermanzohre

2021-09-27 06:34 UTC, recepkoseoglu requested changes

2021-09-27 12:40 UTC, hidayatarg approved these changes

2021-09-27 12:55 UTC, duygusenturk approved these changes

2021-09-27 19:07 UTC, recepkoseoglu requested changes

2021-09-27 19:07 UTC, recepkoseoglu commented on src/components/Table/index.tsx
> +  columns,
rows ve columns değerlerine default boş array verelim

2021-09-27 19:07 UTC, recepkoseoglu commented on src/components/Table/index.tsx
> +                        `${row[column.accessor]}`
row[column.accessor] bu şekilde verelim, true/false gözüksün diye backtick içine koymuştuk

2021-09-27 19:07 UTC, recepkoseoglu commented on src/components/Table/styled.ts
> +export const TableBodyStyled = styled.tbody``
style vermyeceksek kaldırabiliriz tbody yi direk table içinde kullanabiliriz

2021-09-27 19:07 UTC, recepkoseoglu commented on src/components/Table/styled.ts
> +  overflow: hidden;
buna da gerek kaşmaış olabilir kadırıp deneyelim kardıracaksan yine tbody gibi table içinde thead olarak verebiliriz

2021-09-27 19:07 UTC, recepkoseoglu commented on src/stories/Table.stories.tsx
> +        onSort={columnSort}
buraya da console verelim örnek vermeyelim

2021-09-27 19:07 UTC, recepkoseoglu commented on src/stories/Table.stories.tsx
> +        onAddClick={buttonAction}
console verip geçelim

2021-09-27 19:13 UTC, cuneytaskin approved these changes

2021-09-28 09:37 UTC, recepkoseoglu approved these changes

2021-09-28 09:37 UTC, merged