add stepper component
TurkNet/design-system pull request #125
Opened 2021-10-01 21:26 UTC by talatatac

2021-10-02 09:31 UTC, ermanzohre approved these changes

2021-10-02 10:41 UTC, talatatac commented on src/components/Stepper/styled.ts
> +import styled, { css } from 'styled-components'
Bu dosyadaki değşken isimlerinin bazılarına styled eklememişim.

2021-10-04 14:27 UTC, recepkoseoglu requested changes

2021-10-04 14:27 UTC, recepkoseoglu commented on src/components/Stepper/Step.tsx
> +import { noop } from 'src/utility'
relative path olucak

2021-10-04 14:27 UTC, recepkoseoglu commented on src/components/Stepper/Step.tsx
> +const StepLabel: FC<StepLabelProps> = ({
bunun için ayrı bir dosya oluşturalım

2021-10-04 20:47 UTC, recepkoseoglu approved these changes

2021-10-05 07:36 UTC, merged