input-add-icon is done
TurkNet/design-system pull request #135
Opened 2021-10-06 06:23 UTC by ermanzohre

2021-10-06 06:57 UTC, ermanzohre commented on src/components/Input/styled.ts
> +  .material-icons {
icon dışında bir şey koymayız diye düşünerek başlamıştım, burası böyle kalmış. dediğin gibi düzeltiyorum.

2021-10-06 06:58 UTC, ermanzohre commented on src/components/Input/index.tsx
> +  InputHTMLAttributes<HTMLInputElement> & { icon?: ReactNode }
kesinlikle doğru, düzeltiyorum. bu arada icon dışında bir şey gelme durumu var diyorsak ismi de değiştirmem gerekir gibi.

2021-10-06 07:37 UTC, recepkoseoglu requested changes

2021-10-06 07:37 UTC, recepkoseoglu commented on src/components/Input/styled.ts
> +  top: 12px;
```
right: 16px;
top: 50%;
transform: translateY(50%);
```

böyle bir deneyebilir misin

2021-10-07 10:49 UTC, duygusenturk approved these changes

2021-10-07 13:11 UTC, merged