13 DateInput
TurkNet/design-system pull request #171
Opened 2021-11-10 11:07 UTC by recepkoseoglu

2021-11-10 11:20 UTC, cuneytaskin commented on src/components/DateInput/index.tsx
> +        dateFormat="dd/MM/yyyy"
props olarak verilse iyi olur. formatlar değişebilir

2021-11-10 11:21 UTC, ermanzohre approved these changes

2021-11-11 06:03 UTC, recepkoseoglu commented on src/components/DateInput/index.tsx
> +        dateFormat="dd/MM/yyyy"
haklısın

2021-11-11 06:33 UTC, ermanzohre approved these changes

2021-11-11 07:10 UTC, yusufnamdar requested changes
Tarih seçimine ek olarak Saat/zaman seçimi de ekleyebilirmiyiz

2021-11-11 08:00 UTC, cuneytaskin approved these changes

2021-11-11 08:10 UTC, yusufnamdar approved these changes

2021-11-11 09:30 UTC, duygusenturk approved these changes

2021-11-11 10:04 UTC, merged