added again breadcrumb
TurkNet/design-system pull request #273
Opened 2022-01-05 13:24 UTC by birkankervan

2022-01-05 13:37 UTC, yusufnamdar approved these changes

2022-01-05 13:41 UTC, ermanzohre approved these changes

2022-01-05 13:43 UTC, ermanzohre commented
Chromatic neden fail olmuş bir kontrol edebilir misin @birkankervan vaktin olursa.

2022-01-05 13:46 UTC, birkankervan commented
> Chromatic neden fail olmuş bir kontrol edebilir misin @birkankervan vaktin olursa.

olmayan bir props patlatmış storie de

2022-01-06 06:03 UTC, recepkoseoglu requested changes

2022-01-06 06:03 UTC, recepkoseoglu commented on src/components/Breadcrumb/BreadcrumbItem.tsx
> +    <Box ml={16}>{label || children}</Box>
ilk itemda ml olmamalı sanki

2022-01-07 07:36 UTC, ermanzohre approved these changes

2022-01-07 12:03 UTC, ugursepetci approved these changes

2022-01-10 16:24 UTC, recepkoseoglu approved these changes

2022-01-10 17:13 UTC, merged