popover icon check and icon now is centered
TurkNet/design-system pull request #277
Opened 2022-01-11 10:54 UTC by birkankervan

2022-01-11 13:50 UTC, recepkoseoglu requested changes

2022-01-11 13:50 UTC, recepkoseoglu commented on src/components/Input/styled.ts
> -  z-index: ${ifProp('onClick', '0', '-1')};
bunun olması lazımdı select te bu inputu kullanıyor icon click çalışmıyor o durumda

2022-01-12 12:19 UTC, recepkoseoglu approved these changes

2022-01-12 13:09 UTC, ugursepetci approved these changes

2022-01-12 23:00 UTC, merged