add label fix text overflow at mobile
TurkNet/design-system pull request #321
Opened 2022-02-22 15:29 UTC by birkankervan

![image](https://user-images.githubusercontent.com/49693077/155164745-55ca9c71-07a2-46cc-8e7e-91a975355085.png)

2022-02-23 06:10 UTC, ermanzohre reviewed
good job!

2022-02-23 06:10 UTC, ermanzohre approved these changes

2022-02-23 07:36 UTC, recepkoseoglu requested changes

2022-02-23 07:36 UTC, recepkoseoglu commented on src/components/FileUpload/styled.ts
> +  @media screen and (max-width: 575px) {
nop media query kullanmak istemiyoruz

2022-02-23 07:36 UTC, recepkoseoglu commented on src/components/FileUpload/styled.ts
> +  @media screen and (max-width: 575px) {
sadece label'ı props olarak alması yeterli

2022-02-24 06:30 UTC, ermanzohre approved these changes

2022-02-24 13:53 UTC, recepkoseoglu requested changes

2022-02-24 13:53 UTC, recepkoseoglu commented on src/components/FileUpload/styled.ts
> +    width: calc(100vw - 120px);
@birkankervan burda 100vw olmamalı patlar muhtemelen bu başka ekranlada.

2022-02-24 13:53 UTC, recepkoseoglu commented on src/components/FileUpload/styled.ts
> +    width: calc(100vw - 120px);
burda mobil için text göndermeyeceği ya da kısa text göndereceği için elipsis yapmayabiliriz de

2022-02-25 11:57 UTC, birkankervan commented on src/components/FileUpload/styled.ts
> +    width: calc(100vw - 120px);
abi mobilde kısa göndereceğinin garantisi yok ki fotoğraf isimleri uzun olabiliyor bazen.
iconlardaki `owerflow:hidden` ları kaldırıp buna elipsis ekleyince sorun çözülüyor. ama iconlardaki overflowun kalkması sayfa yüklenirken kaymalara sebep olabilir.

2022-02-25 14:11 UTC, recepkoseoglu requested changes

2022-02-25 14:11 UTC, recepkoseoglu commented on src/components/FileUpload/styled.ts
> +    width: calc(100vw - 120px);
tamam elipsis olsun ama calc(100vw - 120px) olmamalı

2022-03-01 12:29 UTC, recepkoseoglu approved these changes

2022-03-01 12:29 UTC, merged