6 buttons
TurkNet/design-system pull request #55
Opened 2021-05-26 23:41 UTC by talatatac

2021-06-03 10:48 UTC, recepkoseoglu reviewed
.idea kolasörünü .gitignore ekleyebilir misin

2021-06-07 06:54 UTC, recepkoseoglu commented on src/components/Button/styled.ts
> +const alphaColor = (color: any): any => Color(color)
bunları ortak bir yere çekecektin, utlis diye

2021-06-07 06:54 UTC, recepkoseoglu commented on src/stories/Button.stories.tsx
> +      <span style={{ paddingRight: '16px' }}>X</span>ButtonName
icon componentsi var artık onu kullanacaktın

2021-06-07 06:54 UTC, recepkoseoglu commented on src/stories/Button.stories.tsx
> +  children: <IconTemplate />,
böyle kullanmayacaktık, zaten içerde icon kullanacaksın burda props olarak vermeyecektik

2021-06-07 06:54 UTC, recepkoseoglu commented on src/components/Button/styled.ts
> +const alphaColor = (color: any): any => Color(color)
```js
const themeColor = (variant: string) => ({ color, theme }: any) => theme.colors[color][variant]
const alphaColor = (alpha: number) => (color: any): any => Color(color).alpha(alpha)

...
background-color: ${themeColor('normal')};
background-color: ${withProp(themeColor('normal'), alphaColor(0.16))};
```

bu şekilde bir saadeleştirme yapabilirsin

2021-06-09 12:19 UTC, recepkoseoglu requested changes

2021-06-09 12:19 UTC, recepkoseoglu commented on src/components/Button/index.tsx
> +export interface ButtonProps
bu şekilde kızıyor olması lazımdı interface tanımlayıp boş verildiğinde. Bu durumda type kullanabilirsin

```js

export type ButtonProps = ButtonStyledProps & HTMLAttributes<HTMLButtonElement>
```

2021-06-09 12:19 UTC, recepkoseoglu commented on src/stories/Button.stories.tsx
> +  ...Template.args,
bu nedendir yiğidim :)

2021-06-09 12:27 UTC, talatatac commented on src/components/Button/styled.ts
> +const alphaColor = (color: any): any => Color(color)
Abi "Utilities.ts" hangi klasör altına açayım? src/Utilities.ts uygun mudur?

2021-06-15 07:38 UTC, recepkoseoglu requested changes

2021-06-15 10:22 UTC, closed without merging