18 tooltips
TurkNet/design-system pull request #59
Opened 2021-06-06 19:19 UTC by ermanzohre

2021-06-07 14:45 UTC, recepkoseoglu requested changes

2021-06-07 14:45 UTC, recepkoseoglu commented on src/components/Tooltip/styled.ts
> +    box-shadow: 0px 0px 10px 0px rgba(0, 0, 0, 0.3);
box shadow theme taşıyabiliriz opacity değerleri standart olmalı demişlerde tarasımda

2021-06-07 14:45 UTC, recepkoseoglu commented on src/components/Tooltip/index.tsx
> +      <span>{children}</span>
TooltipStyled zaten span'dan oluşuyor burda bir daha span vermemize gerek yok sanırım

2021-06-08 09:54 UTC, ermanzohre commented on src/components/Tooltip/styled.ts
> +    box-shadow: 0px 0px 10px 0px rgba(0, 0, 0, 0.3);
konuştuğumuz gibi sadece opacity'i theme'e taşıdım.

2021-06-09 12:15 UTC, recepkoseoglu commented on src/components/Checkbox/styled.ts
> +    opacity: ${theme('opacity.normal')};
opacity için normal, dark çok mantıklı olmamış sanki ayrıca tasarımda 4-5 tane varyasyon vardı. örnek olarak aşağıdaki gibi yapabilirsin

opacity: {
16: '16%',
32: "32%",
48: "48%"
}

2021-06-09 15:24 UTC, talatatac commented on src/components/Tooltip/styled.ts
> +export const variants = {
Variant geneli için; topRight ile topLeft, bottomLeft ile bottomRight içinde tek css attr değişiyorsa bunu bir fonksiyon haline getirmek daha faydalı olur mu?

2021-06-14 13:12 UTC, ermanzohre commented on src/components/Tooltip/styled.ts
> +export const variants = {
okunabilirliği bu şekilde daha iyi gibi olduğu için bırakıyorum bu şekilde.

2021-06-14 13:21 UTC, talatatac approved these changes

2021-06-15 05:54 UTC, recepkoseoglu approved these changes

2021-06-15 06:03 UTC, merged