add alert components
TurkNet/design-system pull request #75
Opened 2021-06-22 21:15 UTC by talatatac

2021-06-23 07:52 UTC, ermanzohre approved these changes

2021-06-23 09:00 UTC, talatatac commented on src/components/Alert/styled.ts
> +  color: 'success' | 'warning' | 'danger' | 'info'
https://material-ui.com/components/alert/ "severity" olarak prop almış. Bunu kullanmak isterim fakat themeColor fonksiyonuna benzer fonksiyon yazmam gerekecek. Burada pratik olarak ne yapabilirim?

2021-06-23 10:42 UTC, recepkoseoglu requested changes

2021-06-24 12:16 UTC, recepkoseoglu approved these changes

2021-06-24 12:17 UTC, merged