add button group components
TurkNet/design-system pull request #77
Opened 2021-06-29 22:50 UTC by talatatac

2021-07-01 10:38 UTC, recepkoseoglu requested changes

2021-07-01 10:38 UTC, recepkoseoglu commented on src/components/ButtonGroup/styled.ts
> +export interface ButtonGroupStyledProps {
ButtonGroupStyled props ihtiyacı yok ki haliyle burda tanımlamana gerek yok burdaki type'ları index içinde verebilirsin.

2021-07-01 10:38 UTC, recepkoseoglu commented on src/components/ButtonGroup/styled.ts
> +export interface ButtonGroupStyledProps {
Ayrıca size, variant, color props'ları Buttonlara ait haliyle  ButtonGroupProps kullanabilirsin

2021-07-01 11:18 UTC, recepkoseoglu requested changes

2021-07-01 11:18 UTC, recepkoseoglu commented on src/components/ButtonGroup/index.tsx
> +export interface ButtonGroupProps {
`export type ButtonGroupProps = ButtonProps` olmalı. böylelikle variant, size ve color type'ları daha düzgün olur sen burda string vermişsin ama normalde enum olmalı

2021-07-01 11:56 UTC, ermanzohre approved these changes

2021-07-01 14:04 UTC, recepkoseoglu requested changes

2021-07-01 14:04 UTC, recepkoseoglu commented on src/components/ButtonGroup/styled.ts
> +    border-radius: ${borderRadius('normal')} 0 0 ${borderRadius('normal')};
```js
border-top-right-radius: 0;
border-bottom-right-radius: 0;
```

olsa daha iyi olur

2021-07-01 14:04 UTC, recepkoseoglu commented on src/components/ButtonGroup/styled.ts
> +    border-radius: 0 ${borderRadius('normal')} ${borderRadius('normal')} 0;
```js
border-top-left-radius: 0;
border-bottom-left-radius: 0;
```

olsa daha iyi olur

2021-07-29 10:36 UTC, recepkoseoglu approved these changes

2021-07-29 10:50 UTC, merged